stages:
  - build
  - test
  - deploy

variables:
  IMAGE_TAG: "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
  KUBE_NAMESPACE: wordpress
  KUBE_CONTEXT: production
  KUBECONFIG_FILE: "$CI_PROJECT_DIR/kubeconfig"
  DEPLOYMENT_NAME: wordpress

before_script:
  - echo "$KUBECONFIG" > $KUBECONFIG_FILE
  - export KUBECONFIG=$KUBECONFIG_FILE
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

test:
  stage: test
  script:
    - echo "Executando PHP Lint nos arquivos..."
    - find wp-content -name "*.php" -exec php -l {} \;

deploy:
  stage: deploy
  only:
    - main
  script:
    - echo "Atualizando imagem no Kubernetes"
    - kubectl -n $KUBE_NAMESPACE set image deployment/$DEPLOYMENT_NAME wordpress=$IMAGE_TAG
