version: '3.9'

services:
  wordpress:
    build: .
    image: registry.tjro.jus.br/docker-hub/wordpress:latest
    ports:
      - "8082:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
    volumes:
      - ./wp-content:/var/www/html/wp-content

  db:
    image: registry.tjro.jus.br/docker-hub/mysql:5.7
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  # wp_content:
  db_data:
